export const GET_ALL_LIST_AND_CARD_DOING = "GET_ALL_LIST_AND_CARD_DOING";
export const GET_ALL_LIST_AND_CARD_SUCCESS = "GET_ALL_LIST_AND_CARD_SUCCESS";
export const GET_ALL_LIST_AND_CARD_FALSE = "GET_ALL_LIST_AND_CARD_FALSE";
